rm -rf "static/themes" "static/global.css"

cat "./node_modules/semantic-ui-css/semantic.min.css" >> "static/global.css"
cp -r "./node_modules/semantic-ui-css/themes" "static"

cat "./node_modules/balloon-css/balloon.min.css" >> "static/global.css"
cat "./node_modules/react-tile-map/lib/styles.css" >> "static/global.css"
cat "./src/decentraland-ui/src/themes/base-theme.css" >> "static/global.css"
cat "./src/decentraland-ui/src/themes/alternative/light-theme.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Button/Button.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Container/Container.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Card/Card.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Dimmer/Dimmer.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Dropdown/Dropdown.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Header/Header.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/HeaderMenu/HeaderMenu.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Modal/Modal.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Loader/Loader.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Pagination/Pagination.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Popup/Popup.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Radio/Radio.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Segment/Segment.css" >> "static/global.css"
cat "./src/decentraland-ui/src/components/Table/Table.css" >> "static/global.css"